/**
 * ONIX List 150 (Product Form) code → human-readable label.
 *
 * Full EDItEUR list, used verbatim. `getProductFormLabel` never fabricates a
 * label for a code it doesn't recognize — it returns null instead, same as
 * for a missing code, so callers can't accidentally surface a wrong guess.
 */
const PRODUCT_FORM_LABELS: Record<string, string> = {
  '00': 'Undefined',
  AA: 'Audio recording – detail unspecified',
  AB: 'Audio cassette (analogue)',
  AC: 'CD-Audio',
  AD: 'Digital audio tape cassette',
  AE: 'Audio disc (excluding CD-Audio)',
  AF: 'Audio tape (analogue open reel)',
  AG: 'Sony MiniDisc format',
  AH: 'Audio CD with part CD-ROM content (Enhanced-CD)',
  AI: 'DVD Audio',
  AJ: 'Digital audio recording downloadable to device(s)',
  AK: 'Pre-recorded digital audio player',
  AL: 'Pre-recorded SD card',
  AM: "'Long player' vinyl disc",
  AN: 'Digital audio: download and online/streamed',
  AO: 'Digital audio: online/streamed only',
  AZ: 'Other audio format',
  BA: 'Book – detail unspecified',
  BB: 'Hardback or cased book',
  BC: 'Paperback or softback book',
  BD: 'Loose-leaf book',
  BE: 'Spiral, comb or coil bound book',
  BF: 'Pamphlet, stapled',
  BG: 'Leather/fine binding',
  BH: "Child's board book",
  BI: "Child's rag book (textile pages)",
  BJ: "Child's bath book (waterproof)",
  BK: 'Novelty book',
  BL: 'Slide bound book',
  BM: 'Extra-large format (Big book)',
  BN: 'Part-work issued with ISBN',
  BO: 'Fold-out/concertina-folded booklet or chart',
  BP: 'Foam book for children',
  BZ: 'Other book format',
  CA: 'Sheet map – detail unspecified',
  CB: 'Sheet map, folded',
  CC: 'Sheet map, flat',
  CD: 'Sheet map, rolled (in tube)',
  CE: 'Globe or planisphere',
  CZ: 'Other cartographic format',
  DA: 'Digital content on physical carrier (unspecified)',
  DB: 'CD-ROM',
  DC: "CD-I ('Green book')",
  DE: 'Game cartridge',
  DF: "Diskette ('floppy disc')",
  DI: 'DVD-ROM',
  DJ: 'Secure Digital (SD) Memory Card',
  DK: 'Compact Flash Memory Card',
  DL: 'Memory Stick Memory Card',
  DM: 'USB Flash Drive',
  DN: 'Double-sided CD/DVD',
  DO: 'BR-ROM (Blu Ray ROM)',
  DZ: 'Other digital carrier',
  EA: 'Digital content delivered electronically (unspecified)',
  EB: 'Digital: download and online/streamed',
  EC: 'Digital: online/streamed only',
  ED: 'Digital download only',
  FA: 'Film or transparency – detail unspecified',
  FC: 'Photographic transparencies for projection',
  FD: 'Overhead projector transparencies',
  FE: 'Photographic filmstrip',
  FF: 'Continuous movie film',
  FZ: 'Other film or transparency format',
  LA: 'Digital product license (delivery unspecified)',
  LB: 'Digital license key (physical card/booklet)',
  LC: 'Digital license code (email/electronic)',
  MA: 'Microform – detail unspecified',
  MB: 'Microfiche',
  MC: 'Roll microfilm',
  MZ: 'Other microform',
  PA: 'Miscellaneous printed material (unspecified)',
  PB: 'Address book',
  PC: 'Calendar',
  PD: 'Cards (flash, revision, playing, trading)',
  PE: 'Copymasters/photocopiable sheets',
  PF: 'Diary or journal',
  PG: 'Frieze',
  PH: 'Kit (assembly parts, construction blocks)',
  PI: 'Sheet music',
  PJ: 'Postcard book or pack',
  PK: 'Poster for retail sale',
  PL: 'Record book (birthday, baby book)',
  PM: 'Wallet, folder or box (loose sheets)',
  PN: 'Pictures or photographs',
  PO: 'Wallchart',
  PP: 'Stickers',
  PQ: 'Plate (book-sized sheet)',
  PR: 'Notebook/blank book',
  PS: 'Organizer',
  PT: 'Bookmark',
  PU: 'Leaflet (folded, unbound)',
  PV: "Book plates ('ex libris' labels)",
  PZ: 'Other printed item',
  SA: 'Multiple-component retail product (unspecified)',
  SB: 'Multiple-component retail product, boxed',
  SC: 'Multiple-component retail product, slip-cased',
  SD: 'Multiple-component retail product, shrink-wrapped',
  SE: 'Multiple-component retail product, loose',
  SF: 'Multiple-component with enclosed part(s)',
  SG: 'Multiple-component product, entirely digital',
  SH: 'Multiple-component product, partly digital',
  VA: 'Video – detail unspecified',
  VF: 'Videodisc (e.g. Laserdisc)',
  VI: 'DVD video',
  VJ: 'VHS videotape',
  VK: 'Betamax videotape',
  VL: 'VideoCD',
  VM: 'Super VideoCD',
  VN: 'HD DVD',
  VO: 'Blu-ray',
  VP: 'Sony Universal Media disc',
  VQ: 'CBHD (China Blue High-Definition)',
  VZ: 'Other video format',
  XA: 'Trade-only material (unspecified)',
  XB: 'Dumpbin – empty',
  XC: 'Dumpbin – filled',
  XD: 'Counterpack – empty',
  XE: 'Counterpack – filled',
  XF: 'Promotional poster (not for sale)',
  XG: 'Shelf strip',
  XH: 'Window display piece',
  XI: 'Streamer',
  XJ: 'Spinner – empty',
  XK: 'Large book display facsimile',
  XL: 'Shrink-wrapped pack (trade supply)',
  XM: 'Boxed pack (trade supply)',
  XN: 'Pack, outer packaging unspecified',
  XO: 'Spinner – filled',
  XY: 'Other point of sale with retail product(s)',
  XZ: 'Other point of sale material',
  ZA: 'General merchandise/book accessories (unspecified)',
  ZB: 'Doll or figure',
  ZC: 'Soft or plush toy',
  ZD: 'Toy (educational toys)',
  ZE: 'Board game or other game',
  ZF: 'T-shirt',
  ZG: 'E-book reader (dedicated device)',
  ZH: 'Tablet computer',
  ZI: 'Audiobook player (dedicated device)',
  ZJ: 'Jigsaw or similar puzzle',
  ZK: 'Mug/cup (branded, promotional)',
  ZL: 'Tote bag (branded, promotional)',
  ZM: 'Tableware (plates, bowls)',
  ZN: 'Umbrella (branded, promotional)',
  ZO: 'Paints, crayons, pencils (coloring sets)',
  ZP: 'Handicraft kit (sewing, weaving, etc.)',
  ZX: 'Other toy/game/puzzle accessories',
  ZY: 'Other apparel items',
  ZZ: 'Other branded/promotional merchandise',
};

/**
 * Returns the human-readable label for a known ONIX List 150 product form
 * code, or null when the code is missing/null/unrecognized. Never guesses.
 */
export function getProductFormLabel(code: string | null | undefined): string | null {
  if (!code) return null;
  return PRODUCT_FORM_LABELS[code] ?? null;
}
